### PR TITLE
Support rescript v11

### PR DESCRIPTION
**Pull request by DZakh**
- Get rid of dependency on Node module

### CODE REVIEW

**Comment by DZakh** [comment]
Solves https://github.com/TheSpyder/rescript-nodejs/issues/15

**Comment by TheSpyder** [comment]
I appreciate you kickstarting this!

Long term I probably need to think about supporting uncurried mode, which looks like it will come alongside a switch to optional record fields for configuration objects, but we'll see what I have time for in the major version change.

The tests didn't compile (reminding me that I need to add CI), the easiest fix was upgrading to `rescript-zora` v4 which now uses `async/await` instead of the new promise bindings. Turned out to be fairly simple once I got the hang of it.

Thanks for enabling maintainer edits, I've just pushed that up - if you're ok with those changes I'll merge it and probably do a beta release on a new major version number.

**Comment by DZakh** [comment]
Looks good!

**Comment by DZakh** [comment]
I've copied the github action from my packages. It should work for now

**Comment by TheSpyder** [comment]
Ah nice, I was wondering which action to use for yarn. I'll merge it and see how we go.

**Comment by DZakh** [comment]
Ah, I've fucked up, haven't noticed that it's the pnpm action. I'll do a PR with a fix

**Comment by TheSpyder** [comment]
I was looking into that after I merged it but then something came up 😆

PR would be appreciated, thank you!

**Pull request merged**
